insert into public.team_name_event_context_quarantine(source,source_name,source_competition,hkjc_event_id,side,team_key,hkjc_name_en,original_status,original_confidence,evidence_sources,quarantine_reason,quarantined_at)
values
('ACC','OH Leuven (W)','UCLW','STATIC:ACC:OHLEUVENW:WRONG:SERVETTE','UNKNOWN','HKJC:servettewomen','Servette Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('ACC','OH Leuven (W)','UCLW','STATIC:ACC:OHLEUVENW:WRONG:STPOLTEN','UNKNOWN','HKJC:stpoltenwomen','St. Polten Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('ACC','Roma (W)','UCLW','STATIC:ACC:ROMAW:WRONG:LYON','UNKNOWN','HKJC:lyonwomen','Lyon Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('ACC','Roma (W)','UCLW','STATIC:ACC:ROMAW:WRONG:MALMO','UNKNOWN','HKJC:malmowomen','Malmo Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('BCL','OH Leuven (W)','UCLW','STATIC:BCL:OHLEUVENW:WRONG:SERVETTE','UNKNOWN','HKJC:servettewomen','Servette Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('BCL','OH Leuven (W)','UCLW','STATIC:BCL:OHLEUVENW:WRONG:STPOLTEN','UNKNOWN','HKJC:stpoltenwomen','St. Polten Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('BCL','Roma (W)','UCLW','STATIC:BCL:ROMAW:WRONG:LYON','UNKNOWN','HKJC:lyonwomen','Lyon Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('BCL','Roma (W)','UCLW','STATIC:BCL:ROMAW:WRONG:MALMO','UNKNOWN','HKJC:malmowomen','Malmo Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('FRB','Lyon W','UCLW','STATIC:FRB:LYONW:WRONG:MALMO','UNKNOWN','HKJC:malmowomen','Malmo Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now()),
('FRB','Servette Chênois W','UCLW','STATIC:FRB:SERVETTEW:WRONG:STPOLTEN','UNKNOWN','HKJC:stpoltenwomen','St. Polten Women','AMBIGUOUS',0,'["ALIAS_REGISTRY_V2","STATIC_WOMEN_COLLISION_REVIEW"]'::jsonb,'STATIC_WRONG_TARGET_WOMEN_COLLISION',now())
on conflict do nothing;

select public.ft_alias_maintenance_v2();
